### ISSUE TITLE
Run Script Error

### ISSUE THREAD

**Issue by EnteraAUsername** [jellyfish-lsef/swm-bugtracker#4]
Everytime i try to run a script it says " Not Injected Cannot Run Scripts While Not Injected " Even Thought Im In Roblo
<img width="1509" alt="Screen Shot 2022-06-17 at 4 19 34 PM" src="https://user-images.githubusercontent.com/104045745/174395948-034a2af6-c732-440d-95f4-144a9940f7e7.png">

**Comment by mistaakyle** [comment]
I'm having this same issue

**Comment by ateball123** [comment]
same bro nobody ever checks this page though did you ever find a solution?

**Comment by foxt** [comment]
Again, this is the bug tracker for the **SWM GUI** and the SWM GUI only. Injection issues are not accepted here as they are developed by two separate people. If you have an injection issue, please select the "Game crashing or scripts not running" button on the new issue page rather than submitting a UI bug report.

Every comment here sends me an email notification, and if it was relevant to this bug tracker I would have responded sooner.

**Comment by Masomum13** [comment]
why is this not working when I inject it and than start a roblox game it just kicks me out
